-- Create Database if not exists
CREATE DATABASE IF NOT EXISTS pork_survey_db;
USE pork_survey_db;

-- Table for Surveys
CREATE TABLE IF NOT EXISTS surveys (
    id INT AUTO_INCREMENT PRIMARY KEY,
    country VARCHAR(100) DEFAULT 'India',
    state VARCHAR(100) DEFAULT 'Karnataka',
    district VARCHAR(100) NOT NULL,
    taluk VARCHAR(150) DEFAULT '',
    village VARCHAR(255) DEFAULT '',
    place VARCHAR(255) NOT NULL,
    pincode VARCHAR(20) NOT NULL,
    shop_name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL,
    owner_mobile VARCHAR(20) DEFAULT '',
    owner_email VARCHAR(150) DEFAULT '',
    shop_ownership VARCHAR(100) DEFAULT '',
    shop_ownership_other VARCHAR(255) DEFAULT '',
    years_in_business INT DEFAULT 0,
    opening_time VARCHAR(50) NOT NULL,
    closing_time VARCHAR(50) NOT NULL,
    holiday_days JSON,
    workers_count VARCHAR(50) NOT NULL,
    daily_customers VARCHAR(50),
    peak_customer_days JSON,
    peak_sales_seasons JSON,
    peak_sales_seasons_other VARCHAR(255) DEFAULT '',
    regular_meat_rate DECIMAL(10, 2) NOT NULL,
    meat_types JSON NOT NULL,
    meat_cuts_sold_most JSON,
    meat_cuts_sold_most_other VARCHAR(255) DEFAULT '',
    processed_meat_consumption JSON,
    average_daily_sale_kg DECIMAL(10, 2) DEFAULT 0,
    unsold_meat_handling JSON,
    unsold_meat_handling_other VARCHAR(255) DEFAULT '',
    storage_capacity VARCHAR(100) DEFAULT '',
    procurement_source VARCHAR(255),
    customer_type VARCHAR(100),
    masalas_available JSON,
    bbmp_license_issued VARCHAR(10) DEFAULT 'No',
    bbmp_license_issues VARCHAR(10) DEFAULT 'No',
    bbmp_issue_reasons TEXT,
    fssai_license_issued VARCHAR(10) DEFAULT 'No',
    fssai_license_issues VARCHAR(10) DEFAULT 'No',
    fssai_issue_reasons TEXT,
    wants_training VARCHAR(10) DEFAULT 'No',
    training_skills JSON,
    training_skills_other VARCHAR(255) DEFAULT '',
    cleanliness_rating INT DEFAULT 3,
    spocs JSON,
    spoc_name VARCHAR(255) DEFAULT '',
    spoc_mobile VARCHAR(20) DEFAULT '',
    location_link TEXT NOT NULL,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    shop_images JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_district (district),
    INDEX idx_pincode (pincode),
    INDEX idx_shop_name (shop_name),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
